### ISSUE TITLE
select Gpu

### ISSUE THREAD

**Issue by windius2022** [sebaxakerhtc/sd-webui-facefusion#10]
hi i have sd next wroking and you extension but it dosnt give me the option to select gpu im using openvino but just installs as cpu

**Comment by sebaxakerhtc** [comment]
> hi i have sd next wroking and you extension but it dosnt give me the option to select gpu im using openvino but just installs as cpu

Hi. Original project haven't support for openvino.
There's nothing to do by me

**Comment by windius2022** [comment]
Ok thanks for info I know the new version has openvino but sd next only has ipex not openvinoSent from my iPhoneOn Aug 1, 2024, at 11:22 AM, sebaxakerhtc ***@***.***> wrote:﻿
Closed #10 as completed.
