### ISSUE TITLE
great - here's something for you, to say thanks 

### ISSUE THREAD

**Issue by chuckkay** [sebaxakerhtc/sd-webui-facefusion#6]
thanks so much.. will keep you updated on any problems
in the mean time i hope you can enjoy this add on i made, for 2.5.2 standalone version.... it adds a host of queueing features, and corrects the output file naming (back to source-target-hash) and elimenates more then just a false for NSFW but actually bypasses the process.........
https://github.com/chuckkay/facefusion-QueueItUp

And if you dont want the whole cloned repo.... you can just download these 3 files..
just download these 3 files:
put this in facefucion\uis\layouts [QueueItUp.py](https://github.com/chuckkay/facefusion-QueueItUp/blob/master/facefusion/uis/layouts/QueueItUp.py) (and call it with "python run.py --ui-layouts QueueItUp" or put it in the facefusion.ini.
and these 2 go in facefusion dir
[content_anyaliser.py](https://github.com/chuckkay/facefusion-QueueItUp/blob/master/facefusion/content_analyser.py)
[normalizer.py](https://github.com/chuckkay/facefusion-QueueItUp/blob/master/facefusion/normalizer.py)

**Comment by sebaxakerhtc** [comment]
@chuckkay NSFW content is unlocked in my version. No need of something else

**Comment by chuckkay** [comment]
> @chuckkay NSFW content is unlocked in my version. No need of something else

i know but my version of content_analyzer skips the analyzing of every frame of video for NSFW which can save user time a 30 min video could take up to 3 mins to analyze, my version skips it instead of just relying on probabilty 10 hack which still checking every frame.

**Comment by sebaxakerhtc** [comment]
Sounds reasonable. Please create a PR with just this check skip

сб, 18 мая 2024 г., 11:54 chuckkay ***@***.***>:
