### ISSUE TITLE
question

### ISSUE THREAD

**Issue by chuckkay** [sebaxakerhtc/sd-webui-facefusion#8]
i understand there were some issues with having facefusion.ini, and you say to use config_user.json but there are some missing items like defaults for which frame_processors etc...  was this ommision also because of errors or just something missed

also i was using this code with face fusion 2.5.* to gather default values at startup, and current values while after selecting source and target.  but with your version i get default values as none for everything with this code snippet. any clue what i should change?

def get_values_from_globals(state_name):
    state_dict = {}
    
    from facefusion.processors.frame import globals as frame_processors_globals, choices as frame_processors_choices

    modules = [facefusion.globals, frame_processors_globals]  

    for module in modules:
        for attr in dir(module):
            if not attr.startswith("__"):
                value = getattr(module, attr)
                try:
                    json.dumps(value)  # Check if the value is JSON serializable
                    state_dict[attr] = value  # Store or update the value in the dictionary
                except TypeError:
                    continue  # Skip values that are not JSON serializable

    return state_dict

**Comment by sebaxakerhtc** [comment]
That's why I deleted default config file - because of errors with "None".
Delete all rows about facefusion in ui-config.Jason and restart the server.

вт, 14 мая 2024 г., 03:23 chuckkay ***@***.***>:
